services:
  - type: web
    name: flask-ticket-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'